name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests
        run: mvn clean test

      - name: Allure Report
        run: |
          npm install -g allure-commandline
          allure generate target/allure-results --clean