# JPA / Hibernate настройки
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Изключваме Kafka Auto-Configuration за API тестовете
# Това спира Spring да търси брокер при стартиране
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

# Позволяваме презаписване на бинове (важно при сложни тестове)
spring.main.allow-bean-definition-overriding=true
spring.kafka.bootstrap-servers=localhost:9092